### ISSUE TITLE
Add missing sets.

### ISSUE THREAD

**Issue by jaaneh** [PokemonTCG/pokemon-tcg-data#173] opened 2021-02-22 20:18 UTC
Hello!
Thanks for providing a great API.

I noticed a couple sets were missing when comparing with TCGplayer, and was wondering if there's plans to add any of them. Most importantly looking at Base Set (Shadowless) personally.

From what I could find, these are the missing sets from the current data. GroupId's are from the TCGplayer API.
```
{
    "groupId": 1455,
    "name": "Best of Promos"
},
{
    "groupId": 2289,
    "name": "Blister Exclusives"
},
{
    "groupId": 1663,
    "name": "Base Set (Shadowless)"
},
{
    "groupId": 609,
    "name": "DP Training Kit 1 Blue"
},
{
    "groupId": 610,
    "name": "DP Training Kit 1 Gold"
},
{
    "groupId": 1543,
    "name": "EX Trainer Kit 1: Latias & Latios"
},
{
    "groupId": 1542,
    "name": "EX Trainer Kit 2: Plusle & Minun"
},
{
    "groupId": 1540,
    "name": "HGSS Trainer Kit: Gyarados & Raichu"
},
{
    "groupId": 2765,
    "name": "SWSH05: Battle Styles"
},
{
    "groupId": 2776,
    "name": "First Partner Pack"
},
{
    "groupId": 2782,
    "name": "McDonald's 25th Anniversary Promos"
},
{
    "groupId": 2686,
    "name": "Battle Academy"
},
{
    "groupId": 2364,
    "name": "McDonald's Promos 2018"
},
{
    "groupId": 2374,
    "name": "Miscellaneous Cards & Products"
},
{
    "groupId": 2282,
    "name": "World Championship Decks"
},
{
    "groupId": 2208,
    "name": "SM Trainer Kit: Alolan Sandslash & Alolan Ninetales"
},
{
    "groupId": 2148,
    "name": "McDonald's Promos 2017"
},
{
    "groupId": 1938,
    "name": "Alternate Art Promos"
},
{
    "groupId": 2069,
    "name": "SM Trainer Kit: Lycanroc & Alolan Raichu"
},
{
    "groupId": 1840,
    "name": "Deck Exclusives"
},
{
    "groupId": 1539,
    "name": "League & Championship Cards"
},
{
    "groupId": 1796,
    "name": "XY Trainer Kit: Pikachu Libre & Suicune"
},
{
    "groupId": 1729,
    "name": "Generations: Radiant Collection"
},
{
    "groupId": 1694,
    "name": "McDonald's Promos 2015"
},
{
    "groupId": 1536,
    "name": "XY Trainer Kit: Latias & Latios"
},
{
    "groupId": 1528,
    "name": "Jumbo Cards"
},
{
    "groupId": 1533,
    "name": "XY Trainer Kit: Bisharp & Wigglytuff"
},
{
    "groupId": 1692,
    "name": "McDonald's Promos 2014"
},
{
    "groupId": 1532,
    "name": "XY Trainer Kit: Sylveon & Noivern"
},
{
    "groupId": 1465,
    "name": "Legendary Treasures: Radiant Collection"
},
{
    "groupId": 1538,
    "name": "BW Trainer Kit: Excadrill & Zoroark"
},
{
    "groupId": 2332,
    "name": "Professor Program Promos"
},
{
    "groupId": 2205,
    "name": "Pikachu World Collection Promos"
},
{
    "groupId": 2175,
    "name": "Burger King Promos"
},
{
    "groupId": 2155,
    "name": "Countdown Calendar Promos"
},
{
    "groupId": 1541,
    "name": "DP Trainer Kit: Manaphy & Lucario"
},
{
    "groupId": 1853,
    "name": "EX Battle Stadium"
},
{
    "groupId": 2214,
    "name": "Kids WB Promos"
}
```

**Comment by CptSpaceToaster** [comment] 2021-03-17 15:33
:one: Shadowless isn't a missing set. Shadowless is a different print run of the Base Set (which exists in the API). The Base Set had 4 print-runs, and had 3 notable changes in the card's artwork and manufacturing. Occasionally there has been talk about surfacing the print runs for sets like Base Set in the API somehow... but for now, you're going to have to special case Base Set somehow locally in your application. https://relentlessdragon.com/pokemon-card-game/identifying-early-pokemon-cards/

:two: Sword & Shield—Battle Styles isn't out yet. Wait 2 more days.

:three: Generations: Radiant Collection is a subset of Generations. You'll find all of these cards in `/sets/g1`. All of the card numbers are prefixed with RC like they are on the card. Chikorita is here: https://api.pokemontcg.io/v2/cards/g1-RC1

:four: Legendary Treasures: Radiant Collection is a subset of Legendary Treasures. You'll find all of these cards in `/sets/bw11`. All of the card numbers are prefixed with RC like they are on the card. Snivy is here: https://api.pokemontcg.io/v2/cards/bw11-RC1

:five: The Best of Promos set is a duplicate of https://github.com/PokemonTCG/pokemon-tcg-data/pull/158/files

:six: Mcdonald's promos are already noted in https://github.com/PokemonTCG/pokemon-tcg-data/issues/183 and https://github.com/PokemonTCG/pokemon-tcg-data/issues/81

:seven: Jumbo cards - I'm pretty sure we don't care about these? This would include the Jumbo exclusives in the First Partner Packs.

:eight: The trainer kits are stand-alone 30 card decks... with their own set numbers and set symbol. They are definitely "missing"... but every card in the trainer kit is a duplicate from sets released during that time, so in terms of the "list of cards" there aren't any functional cards that are missing in the API, but in terms of the "complete set numbers" we're technically missing them. Duplicate of: https://github.com/PokemonTCG/pokemon-tcg-data/issues/81

Likewise, the world championship decks seem like they'd be out of place in the API. They're technically missing... but not exactly cards that are functionally missing aside from a collecting standpoint.

:nine: TCG Player made the "Blister exclusive" and "Deck Exclusives" groups to track cards that exist in sets, but have a unique quality about them in how they were released. Oftentimes, this will simply be a different holofoil pattern, and oftentimes, these cards are released as exclusives in the front of a 3 pack combo or a shatter-holo in a deck. Again, these are technically missing, but the cards themselves functionally exist in the API already. I don't know how to best handle these... other than maybe noting which cards have different foil patterns?

These groups are the ones I have left. I suspect a lot of them are going to be similar changes to a holo pattern of a card that's already represented somehow.
```{
    "groupId": 2374,
    "name": "Miscellaneous Cards & Products"
},
{
    "groupId": 1938,
    "name": "Alternate Art Promos"
},
{
    "groupId": 1539,
    "name": "League & Championship Cards"
},
{
    "groupId": 2332,
    "name": "Professor Program Promos"
},
{
    "groupId": 2205,
    "name": "Pikachu World Collection Promos"
},
{
    "groupId": 2175,
    "name": "Burger King Promos"
},
{
    "groupId": 2155,
    "name": "Countdown Calendar Promos"
},
{
    "groupId": 2214,
    "name": "Kids WB Promos"
}```

**Comment by adback03** [comment] 2021-12-16 17:48
I'm going to close this issue as we have a lot of these sets called out elsewhere, and would prefer to track each missing set as a separate issue. If you notice any set missing that you still believe should be added, feel free to make an issue per set so each can be tracked individually and easier for others to contribute to.

Thank you!

**Closed by adback03** 2021-12-16 17:48 UTC
