### ISSUE TITLE
When using orderBy=number to fetch Unseen forces's Unowns, the cards are unordered unless your search's pageSize is in excess of the number of cards found.

### ISSUE THREAD

**Issue by Pepper0ni** [PokemonTCG/pokemon-tcg-data#232] opened 2021-11-05 14:26 UTC
As title.
Unusually the order is correct to a number sort by default (as it is on every set I have tested other than Celebrations) so attempting to sort by number actually unsorts the cards relative to not specifying an order which is clearly unintended. 

An example of the output after "sorting" https://cdn.discordapp.com/attachments/806542736777674812/906186386112127026/unknown.png

**Comment by CptSpaceToaster** [comment] 2021-11-05 14:52
Pushing to close this as a "can't reproduce" albeit... not immediately.

I'm able to `GET` on `https://api.pokemontcg.io/v2/cards?q=set.id:ex10&orderBy=number` and in order... I receive:

- 28 Unown [A-Z][!][?]
- all remaining cards 1-117

This set is notoriously tricky however... because pokemon decided to "number" the cards with letters and symbols. This has made a lot of people very angry and been widely regarded as a bad move.

Chances are, whatever you are using to parse the results after they are being ordered is somehow throwing the cards into disarray. Even if you handle the "numbers" like "A" and "B" correctly... handling the "numbers" "!" and "?" can cause a lot of errors in various applications that were assuming they were just............ integers.

**Comment by CptSpaceToaster** [comment] 2021-11-05 15:05
Looks like there _is_ a bug related to how the alphabetical sort is applied to the page size. If you don't request the entire page in one request... then _unknown specifically_ get all jumbled up. The rest of the cards are still in numeric order. Sounds like a bad optimization hiding somewhere.

`GET` `https://api.pokemontcg.io/v2/cards?q=set.id:ex10&orderBy=number&pageSize=146`
works

`GET` `https://api.pokemontcg.io/v2/cards?q=set.id:ex10&orderBy=number&pageSize=145`
doesn't

Amazing find!

**Comment by CptSpaceToaster** [comment] 2021-11-05 15:10
Similarly
`GET` `https://api.pokemontcg.io/v2/cards?q=name:unown&orderBy=number&pageSize=91`
works

`GET` `https://api.pokemontcg.io/v2/cards?q=name:unown&orderBy=number&pageSize=90`
doesn't

**Comment by CptSpaceToaster** [comment] 2021-11-05 15:15
Fun fact: the pageSize is off by one:
Unseen Forces only has 145 cards... but you specifically have to request _146_
same with the unown query... there are only 90 unowns... but you have to request _91_

**Comment by adback03** [comment] 2021-12-17 01:14
This has been fixed. I ran through the scenarios the @CptSpaceToaster pointed out, and no longer run into them. The unowns are now ordered correctly in Unseen Forces, and you no longer have to request pageSize of 146 to get all 145, etc.,

**Closed by adback03** 2021-12-17 01:14 UTC
Labels: bug, investigating
